issues:
  exclude:
    # False positive for table tests
    # https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope .* in function literal

linters:
  enable:
    - megacheck
    - govet
    - gofmt
  disable:
    - maligned
    - prealloc
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false

