/*
 * sayhi web service
 *
 * A polite web service that always says hello
 *
 * API version: 1.0.0
 * Contact: marco.micera+sayhi@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"time"

	sw "github.com/marcomicera/sayhi/go"
)

type logWriter struct {
}

// Custom log format includes ISO date
func (writer logWriter) Write(bytes []byte) (int, error) {
	return fmt.Print(time.Now().Format(time.RFC3339) + " " + string(bytes))
}

func main() {

	// Using custom log format
	log.SetFlags(0)
	log.SetOutput(new(logWriter))

	log.Printf("Server started")

	router := sw.NewRouter()

	port := flag.Int("port", 8080, "Web service port")
	flag.Parse()
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%d", *port), router))
}
