/*
 * sayhi web service
 *
 * A polite web service that always says hello
 *
 * API version: 1.0.0
 * Contact: marco.micera+sayhi@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sayhi

import (
	"encoding/json"
	"fmt"
	"github.com/marcomicera/sayhi/go/stringutils"
	"net/http"
	"strings"
)

var GitCommit string
var ProjectName string

func GetProjectInfo(w http.ResponseWriter, r *http.Request) {

	// Retrieving project information
	var info ProjectInfo
	info.GitHash = GitCommit
	info.ProjectName = ProjectName

	// Building response message
	js, err := json.Marshal(info)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	_, err = w.Write(js)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
	}
}

func SayHi(w http.ResponseWriter, r *http.Request) {

	// Getting the right person's name
	person := "Stranger"
	if name, ok := r.URL.Query()["name"]; ok {
		person = stringutils.SplitCamelCase(strings.Join(name, " "))
	}

	// Building response message
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	_, err := fmt.Fprintf(w, "Hello %s", person)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
	}
}
