/*
 * sayhi web service
 *
 * A polite web service that always says hello
 *
 * API version: 1.0.0
 * Contact: marco.micera+sayhi@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sayhi

import (
	"fmt"
	"github.com/marcomicera/sayhi/go/stringutils"
	"net/http"
	"strings"
)

func GetProjectInfo(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func SayHi(w http.ResponseWriter, r *http.Request) {

	// Getting the right person's name
	person := "Stranger"
	if name, ok := r.URL.Query()["name"]; ok {
		person = stringutils.SplitCamelCase(strings.Join(name, " "))
	}

	// Building response message
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	_, err := fmt.Fprintf(w, "Hello %s", person)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
	}
}
